### ISSUE TITLE
Mangahub Doesn’t open

### ISSUE THREAD

**Issue by CalvinDon** [TheNetsky/Netskys-Extensions#42] opened 2022-08-18 18:24 UTC
**Describe the bug**
The Mangahub source doesn’t show any mangas except gives a JSError pop up

**To Reproduce**
1. Go to 'Search’
2. Click on 'Mangahub’
3. See error pop up

**Expected behavior**
Manga list should appear

**Screenshots/Video**
If applicable, add screenshots to help explain your problem

**App version**
- v0.7-r46

**Source WITH source version**
- Mangahub v2.0.7

**Additional context**
The other extensions related to this source repo are working fine

**Comment by TheNetsky** [comment] 2022-08-18 18:25
Dupe of #40

**Closed as completed by TheNetsky** 2022-08-18 18:25 UTC
Labels: bug
