### ISSUE TITLE
No automatic updates from sources

### ISSUE THREAD

**Issue by chailjc** [TheNetsky/Netskys-Extensions#45] opened 2022-08-24 05:58 UTC
**Describe the bug**
Mangabuddy, AsuraScans, ReaperScans, FlameScans comics in "Library" don't automatically update nor show notifications even after refreshing/restarting app r47 version

**To Reproduce**
1. Go to 'Library'
2. Scroll down to refresh saved sources
3. No updates appear for Mangabuddy, AsuraScans, ReaperScans, FlameScans

**Expected behavior**
Update notifications to appear for saved comics

**App version**
- v0.7-r47

**Source WITH source version**
- Mangabuddy 1.1.1
- AsuraScans 2.1.9
- ReaperScans 2.2.4
- FlameScans 2.0.4

**Additional context**
Here are some methods I tried to see if I can get notifications:

1. Left app in background
2. Migrating saved comics to same sources (e.g. AsuraScans > AsuraScans)
3. Restarting app
4. Reinstalling app

However, notifications for other sources (Readm, Mangakakalot) still appear

**Comment by TheNetsky** [comment] 2022-08-24 07:25
Duplicate of so many issues. Read the previous ones next time. This is an app issue, not a source issue. Will be fixed with 0.8.

**Closed as completed by TheNetsky** 2022-08-24 07:25 UTC
Labels: bug
